### ISSUE TITLE
integracao com nopcommerce

### ISSUE THREAD

**Issue by marcelowu** [matmiranda/PicPay-NET#1]
integra  commerce.

**Comment by matmiranda** [comment]
Pode explicar com mais detalhes?

**Comment by marcelowu** [comment]
https://github.com/nopSolutions/nopCommerce
Free open-source ecommerce shopping cart (ASP.NET Core) https://www.nopcommerce.com

**Comment by marcelowu** [comment]
vc faz um  plugins de pagamento para grandnode ?
https://docs.grandnode.com/how-to-create-payment-type-plugin
